site_name: NetBox
theme: readthedocs
repo_url: https://github.com/netbox-community/netbox

pages:
    - Introduction: 'index.md'
    - Installation:
        - Installing NetBox: 'installation/index.md'
        - 1. PostgreSQL: 'installation/1-postgresql.md'
        - 2. NetBox: 'installation/2-netbox.md'
        - 3. HTTP Daemon: 'installation/3-http-daemon.md'
        - 4. LDAP (Optional): 'installation/4-ldap.md'
        - Upgrading NetBox: 'installation/upgrading.md'
        - Migrating to Python3: 'installation/migrating-to-python3.md'
    - Configuration:
        - Configuring NetBox: 'configuration/index.md'
        - Required Settings: 'configuration/required-settings.md'
        - Optional Settings: 'configuration/optional-settings.md'
    - Core Functionality:
        - IP Address Management: 'core-functionality/ipam.md'
        - VLANs: 'core-functionality/vlans.md'
        - Sites and Racks: 'core-functionality/sites-and-racks.md'
        - Devices: 'core-functionality/devices.md'
        - Virtual Machines: 'core-functionality/virtual-machines.md'
        - Services: 'core-functionality/services.md'
        - Circuits: 'core-functionality/circuits.md'
        - Secrets: 'core-functionality/secrets.md'
        - Tenancy: 'core-functionality/tenancy.md'
    - Additional Features:
        - Tags: 'additional-features/tags.md'
        - Custom Fields: 'additional-features/custom-fields.md'
        - Context Data: 'additional-features/context-data.md'
        - Export Templates: 'additional-features/export-templates.md'
        - Graphs: 'additional-features/graphs.md'
        - Topology Maps: 'additional-features/topology-maps.md'
        - Reports: 'additional-features/reports.md'
        - Webhooks: 'additional-features/webhooks.md'
        - Change Logging: 'additional-features/change-logging.md'
        - Caching: 'additional-features/caching.md'
        - Prometheus Metrics: 'additional-features/prometheus-metrics.md'
    - Administration:
        - Replicating NetBox: 'administration/replicating-netbox.md'
        - NetBox Shell: 'administration/netbox-shell.md'
    - API:
        - Overview: 'api/overview.md'
        - Authentication: 'api/authentication.md'
        - Working with Secrets: 'api/working-with-secrets.md'
        - Examples: 'api/examples.md'
    - Development:
        - Introduction: 'development/index.md'
        - Style Guide: 'development/style-guide.md'
        - Utility Views: 'development/utility-views.md'
        - Extending Models: 'development/extending-models.md'
        - Release Checklist: 'development/release-checklist.md'

markdown_extensions:
    - admonition:
